import { IProject } from '@/types';

export const GENERAL_INFO = {
    name: 'Muhammad Ashikuzzaman',
    email: 'ashik.chowdhury79@gmail.com',
    phone: '+880 1632035033',
    linkedin: 'https://linkedin.com/in/muhammad-ashikuzzaman',
    emailSubject: "Let's collaborate on a project",
    emailBody: 'Hi Ashik, I am reaching out to you because...',
    upworkProfile: 'https://linkedin.com/in/muhammad-ashikuzzaman',
};

export const SOCIAL_LINKS = [
    { name: 'github', url: 'https://github.com/muhammad-ashik' },
    { name: 'linkedin', url: GENERAL_INFO.linkedin },
    { name: 'facebook', url: 'https://www.facebook.com/adrian.ahsin' },
    { name: 'whatsapp', url: 'https://wa.me/8801632035033' },
];
export const MY_STACK = {
    languages: [
        { name: 'JavaScript', icon: '/logo/js.png' },
        { name: 'TypeScript', icon: '/logo/ts.png' },
    ],
    frameworks: [
        { name: 'React', icon: '/logo/react.png' },
        { name: 'Next.js', icon: '/logo/next.png' },
        { name: 'Vue.js', icon: '/logo/vue.png' },
        { name: 'React Native', icon: '/logo/react.png' },
    ],
    'State Mgmt': [
        { name: 'Redux', icon: '/logo/redux.png' },
        { name: 'Pinia', icon: '/logo/pinia.svg' },
        { name: 'Vuex', icon: '/logo/vue.png' },
        { name: 'Zustand', icon: '/logo/react.png' },
    ],
    'Backend & API': [
        { name: 'Node.js', icon: '/logo/node.png' },
        { name: 'Express.js', icon: '/logo/express.png' },
        { name: 'REST APIs', icon: '/logo/js.png' },
        { name: 'GraphQL', icon: '/logo/js.png' },
    ],
    'UI & Styling': [
        { name: 'Tailwind CSS', icon: '/logo/tailwind.png' },
        { name: 'Material UI', icon: '/logo/mui.png' },
        { name: 'Vuetify', icon: '/logo/vue.png' },
        { name: 'Sass', icon: '/logo/sass.png' },
    ],
    'DevOps & CI/CD': [
        { name: 'Docker', icon: '/logo/docker.svg' },
        { name: 'Kubernetes', icon: '/logo/k8s.svg' },
        { name: 'ArgoCD', icon: '/logo/argocd.svg' },
        { name: 'GitHub Actions', icon: '/logo/github.png' },
    ],
    monitoring: [
        { name: 'Datadog', icon: '/logo/node.png' },
        { name: 'Sentry', icon: '/logo/node.png' },
        { name: 'LogRocket', icon: '/logo/node.png' },
    ],
    databases: [
        { name: 'PostgreSQL', icon: '/logo/postgreSQL.png' },
        { name: 'TypeORM', icon: '/logo/ts.png' },
    ],
    'AI Tools': [
        { name: 'Claude AI', icon: '/logo/js.png' },
        { name: 'Cursor', icon: '/logo/js.png' },
    ],
    tools: [
        { name: 'Git', icon: '/logo/git.png' },
        { name: 'Jira', icon: '/logo/jira.svg' },
        { name: 'Agile/Scrum', icon: '/logo/jira.svg' },
        { name: 'Storybook', icon: '/logo/react.png' },
        { name: 'Vite', icon: '/logo/js.png' },
        { name: 'Webpack', icon: '/logo/js.png' },
    ],
};

export const PROJECTS: IProject[] = [
    {
        title: 'Bolgany — Premium Real Estate',
        slug: 'bolgany-real-estate',
        techStack: ['React', 'Next.js', 'Tailwind CSS'],
        thumbnail: '/assets/Bolgany Real Estate.jpeg',
        longThumbnail: '/projects/long/bolgany.webp',
        images: [],
        liveUrl: 'https://bolgany-realestate.de/',
        year: 2024,
        description: `A premium real estate platform for the German market, featuring property listings and interactive maps.`,
        role: `Frontend Developer`,
    },
    {
        title: 'ZKB — Financial Web Platform',
        slug: 'zkb-financial',
        techStack: ['TypeScript', 'Vue.js', 'Vuetify', 'Keycloak'],
        thumbnail: '/assets/ZKB.jpeg',
        longThumbnail: '/projects/long/zkb.webp',
        images: [],
        liveUrl: 'https://zertifikate.zkb.ch/',
        year: 2024,
        description: `Investment product visualization with secure auth and dynamic data handling for institutional clients.`,
        role: `Software Engineer`,
    },
    {
        title: 'L\'académie des Bébés',
        slug: 'lacademiedesbebes',
        techStack: ['Vue.js', 'Nuxt.js', 'Sass'],
        thumbnail: '/assets/L\'académie des Bébés.jpeg',
        longThumbnail: '/projects/long/babies.webp',
        images: [],
        liveUrl: 'https://lacademiedesbebes.com/',
        year: 2024,
        description: `Educational platform focused on early childhood development and infant care.`,
        role: `Frontend Developer`,
    },
    {
        title: 'Flowcode TV — Cloud Video Editor',
        slug: 'flowcode-tv',
        techStack: ['React', 'Remotion', 'Node.js'],
        thumbnail: '/assets/FlowCode-TV.webp',
        longThumbnail: '/projects/long/flowcode.webp',
        images: [],
        liveUrl: '#',
        year: 2023,
        description: `Browser-based editor with real-time Lottie overlays, live preview, and 4K export.`,
        role: `Software Developer`,
    },
    {
        title: 'iPlanner — Outlook Integration',
        slug: 'iplanner-outlook',
        techStack: ['Next.js', 'REST API', 'Fluent UI'],
        thumbnail: '/assets/iPlanner-Outlook-and-Team-App-740x414.webp',
        longThumbnail: '/projects/long/dfl.webp',
        images: [],
        liveUrl: '#',
        year: 2024,
        description: `Complex Outlook and Teams integration for enterprise project management and scheduling.`,
        role: `Software Engineer`,
    },
    {
        title: 'Flow Leads — Lead Management',
        slug: 'flow-leads',
        techStack: ['React.js', 'Node.js', 'Express.js'],
        thumbnail: '/assets/FlowLeads.webp',
        longThumbnail: '/projects/long/flow-leads.webp',
        images: [],
        liveUrl: '#',
        year: 2023,
        description: `End-to-end lead tracking and nurturing tools for marketing and sales teams.`,
        role: `Software Developer`,
    },
    {
        title: 'DFL Project Manager',
        slug: 'dfl-project-manager',
        techStack: ['Next.js', 'Fluent UI', 'Planner API'],
        thumbnail: '/assets/DFL.webp',
        longThumbnail: '/projects/long/dfl.webp',
        images: [],
        liveUrl: '#',
        year: 2024,
        description: `Real-time resource allocation and project tracking for enterprise teams.`,
        role: `Software Engineer`,
    },
    {
        title: 'Property Pro — Sales Automation',
        slug: 'property-pro',
        techStack: ['Next.js', 'PostgreSQL', 'Prisma'],
        thumbnail: '/projects/thumbnail/property-pro.jpg',
        longThumbnail: '/projects/long/property-pro.webp',
        images: [],
        liveUrl: '#',
        year: 2024,
        description: `Automated property valuation and lead nurturing system for real estate brokers.`,
        role: `Lead Developer`,
    },
];

export const MY_EXPERIENCE = [
    {
        title: 'Software Engineer L3',
        company: 'WSD',
        role_type: 'engineer-l3',
        duration: 'Feb 2026 – Present',
        location: 'Germany · Remote',
    },
    {
        title: 'Frontend Developer',
        company: 'WSD',
        role_type: 'frontend-dev',
        duration: 'Oct 2024 – Feb 2026',
        location: 'Germany · Remote',
    },
    {
        title: 'Software Engineer',
        company: 'Ixora Solution Limited',
        role_type: 'software-engineer',
        duration: 'Jan 2023 – Aug 2024',
        location: 'Dhaka, Bangladesh · On-site',
    },
    {
        title: 'Software Developer',
        company: 'Ixora Solution Limited',
        role_type: 'software-developer',
        duration: 'Sep 2021 – Jan 2023',
        location: 'Dhaka, Bangladesh · On-site',
    },
    {
        title: 'Frontend Developer',
        company: 'Business Technology',
        role_type: 'frontend-dev-bt',
        duration: 'Apr 2020 – Aug 2021',
        location: 'Dhaka, Bangladesh · On-site',
    },
];
