import { IProject } from '@/types';

export const GENERAL_INFO = {
    name: 'Muhammad Ashikuzzaman',
    email: 'ashik.chowdhury79@gmail.com',
    phone: '+880 1632035033',
    linkedin: 'https://linkedin.com/in/muhammad-ashikuzzaman',
    emailSubject: "Let's collaborate on a project",
    emailBody: 'Hi Ashik, I am reaching out to you because...',
    upworkProfile: 'https://linkedin.com/in/muhammad-ashikuzzaman',
};

export const SOCIAL_LINKS = [
    { name: 'linkedin', url: GENERAL_INFO.linkedin },
    { name: 'facebook', url: 'https://www.facebook.com/adrian.ahsin' },
    { name: 'whatsapp', url: 'https://wa.me/8801632035033' },
];

export const MY_STACK = {
    languages: [
        { name: 'JavaScript', icon: '/logo/js.png' },
        { name: 'TypeScript', icon: '/logo/ts.png' },
    ],
    frameworks: [
        { name: 'React', icon: '/logo/react.png' },
        { name: 'Next.js', icon: '/logo/next.png' },
        { name: 'Vue.js', icon: '/logo/vue.png' },
        { name: 'Nuxt.js', icon: '/logo/next.png' },
        { name: 'React Native', icon: '/logo/react.png' },
    ],
    backend: [
        { name: 'Node.js', icon: '/logo/node.png' },
        { name: 'Express.js', icon: '/logo/express.png' },
        { name: 'Rest API', icon: '/logo/node.png' },
        { name: 'GraphQL', icon: '/logo/node.png' },
    ],
    rendering: [
        { name: 'SSR', icon: '/logo/next.png' },
        { name: 'SSG', icon: '/logo/next.png' },
        { name: 'Micro-Frontends', icon: '/logo/react.png' },
    ],
    styling: [
        { name: 'Tailwind CSS', icon: '/logo/tailwind.png' },
        { name: 'Material UI', icon: '/logo/mui.png' },
        { name: 'Vuetify', icon: '/logo/vue.png' },
        { name: 'Sass', icon: '/logo/sass.png' },
    ],
    devops: [
        { name: 'Docker', icon: '/logo/docker.svg' },
        { name: 'Kubernetes', icon: '/logo/k8s.png' },
        { name: 'ArgoCD', icon: '/logo/argocd.png' },
        { name: 'GitHub Actions', icon: '/logo/git.png' },
    ],
    monitoring: [
        { name: 'Datadog', icon: '/logo/node.png' },
        { name: 'Sentry', icon: '/logo/node.png' },
    ],
    tools: [
        { name: 'Git', icon: '/logo/git.png' },
        { name: 'Jira', icon: '/logo/jira.svg' },
        { name: 'Storybook', icon: '/logo/react.png' },
        { name: 'Claude AI', icon: '/logo/js.png' },
        { name: 'Cursor', icon: '/logo/js.png' },
    ],
};

export const PROJECTS: IProject[] = [
    {
        title: 'ZKB — Financial Web Platform',
        slug: 'zkb-financial',
        liveUrl: 'https://zertifikate.zkb.ch/',
        year: 2024,
        description: `Investment product visualization with secure auth and dynamic data handling for thousands of users. Built using TypeScript, Vue.js, and Vuetify with Keycloak integration.`,
        role: `Software Engineer <br/> Worked on secure data handling and visualization for financial products.`,
        techStack: ['TypeScript', 'Vue.js', 'Vuetify', 'Keycloak'],
        thumbnail: '/projects/thumbnail/zkb.webp',
        longThumbnail: '/projects/long/zkb.webp',
        images: [],
    },
    {
        title: 'Flowcode TV — Cloud Video Editor',
        slug: 'flowcode-tv',
        techStack: ['React', 'Remotion', 'Lottie', 'Node.js'],
        thumbnail: '/projects/thumbnail/flowcode.webp',
        longThumbnail: '/projects/long/flowcode.webp',
        images: [],
        liveUrl: '#',
        year: 2023,
        description: `Browser-based editor with real-time Lottie overlays, live preview, and 4K export. Engineered a real-time preview engine with Lottie animations, text overlays, and QR code support.`,
        role: `Software Developer <br/> Engineered the rendering pipeline and real-time preview engine.`,
    },
    {
        title: 'Bolgany Real Estate',
        slug: 'bolgany-real-estate',
        techStack: ['React', 'Next.js', 'Tailwind CSS'],
        thumbnail: '/projects/thumbnail/bolgany.webp',
        longThumbnail: '/projects/long/bolgany.webp',
        images: [],
        liveUrl: 'https://bolgany-realestate.de/',
        year: 2024,
        description: `A premium real estate platform for the German market, featuring property listings and interactive maps.`,
        role: `Frontend Developer`,
    },
    {
        title: 'L\'académie des Bébés',
        slug: 'lacademiedesbebes',
        techStack: ['Vue.js', 'Nuxt.js', 'Sass'],
        thumbnail: '/projects/thumbnail/babies.webp',
        longThumbnail: '/projects/long/babies.webp',
        images: [],
        liveUrl: 'https://lacademiedesbebes.com/',
        year: 2024,
        description: `Educational platform focused on early childhood development and infant care.`,
        role: `Frontend Developer`,
    },
    {
        title: 'Flow Leads — Lead Management',
        slug: 'flow-leads',
        techStack: ['React.js', 'Node.js', 'Express.js'],
        thumbnail: '/projects/thumbnail/flow-leads.webp',
        longThumbnail: '/projects/long/flow-leads.webp',
        images: [],
        liveUrl: '#',
        year: 2023,
        description: `End-to-end lead tracking, nurturing, and conversion tools for marketing and sales teams.`,
        role: `Software Developer`,
    },
    {
        title: 'DFL Project Manager',
        slug: 'dfl-project-manager',
        techStack: ['Next.js', 'Fluent UI', 'Planner REST API'],
        thumbnail: '/projects/thumbnail/dfl.webp',
        longThumbnail: '/projects/long/dfl.webp',
        images: [],
        liveUrl: '#',
        year: 2024,
        description: `Real-time resource allocation with drag-and-drop scheduling and visual calendars.`,
        role: `Software Engineer`,
    },
    {
        title: 'myTask2do — Task Manager',
        slug: 'mytask2do',
        techStack: ['React', 'Node.js', 'PostgreSQL'],
        thumbnail: '/projects/thumbnail/mytask2do.webp',
        longThumbnail: '/projects/long/mytask2do.webp',
        images: [],
        liveUrl: '#',
        year: 2022,
        description: `Collaborative task management platform unifying workflows and boosting team accountability.`,
        role: `Full-Stack Developer`,
    },
    {
        title: 'EyeGuard — Smart Monitor',
        slug: 'eyeguard',
        techStack: ['React Native', 'Expo', 'Camera API'],
        thumbnail: '/projects/thumbnail/eyeguard.webp',
        longThumbnail: '/projects/long/eyeguard.webp',
        images: [],
        liveUrl: '#',
        year: 2024,
        description: `Mobile app for eye-to-screen distance monitoring with intelligent alerts.`,
        role: `Mobile Developer`,
    },
];

export const MY_EXPERIENCE = [
    {
        title: 'Software Engineer L3',
        company: 'WSD',
        role_type: 'engineer-l3',
        duration: 'Feb 2026 – Present',
        location: 'Germany · Remote',
    },
    {
        title: 'Frontend Developer',
        company: 'WSD',
        role_type: 'frontend-dev',
        duration: 'Oct 2024 – Feb 2026',
        location: 'Germany · Remote',
    },
    {
        title: 'Software Engineer',
        company: 'Ixora Solution Limited',
        role_type: 'software-engineer',
        duration: 'Jan 2023 – Aug 2024',
        location: 'Dhaka, Bangladesh · On-site',
    },
    {
        title: 'Software Developer',
        company: 'Ixora Solution Limited',
        role_type: 'software-developer',
        duration: 'Sep 2021 – Jan 2023',
        location: 'Dhaka, Bangladesh · On-site',
    },
    {
        title: 'Frontend Developer',
        company: 'Business Technology',
        role_type: 'frontend-dev-bt',
        duration: 'Apr 2020 – Aug 2021',
        location: 'Dhaka, Bangladesh · On-site',
    },
];
